import type { Dataset } from "./schema";
export function createWorkspace(
  id: string,
  name: string,
  user: { id: string; name: string; email: string },
  now: number,
  organizationId = id,
): Dataset {
  const base = { workspaceId: id };
  return {
    workspace: {
      ...base,
      id,
      name,
      organizationId,
      timezone: "UTC",
      mode: "copilot",
      paused: false,
      active: false,
      createdAt: now,
    },
    workspaceMembers: [
      {
        ...base,
        id: `member-${user.id}`,
        userId: user.id,
        email: user.email,
        name: user.name,
        role: "owner",
      },
    ],
    businessProfiles: [
      {
        ...base,
        id: "business-profile",
        name,
        website: "",
        description: "",
        goal: "Activation recovery",
        icp: "Developer-first companies",
        exclusions: [],
        approvedClaims: [],
        writingRules: [
          "Lead with a useful next step.",
          "Keep the message short and specific.",
          "Use verified facts only.",
        ],
        prohibitedPhrases: [
          "Hope this email finds you well",
          "just circling back",
          "bumping this",
          "I noticed that",
        ],
        offer: "Implementation help",
        cta: "https://example.com/docs",
        confirmed: false,
        pageStrategy: "qualified",
      },
    ],
    brandProfiles: [
      {
        ...base,
        id: "brand-1",
        version: 1,
        name,
        primary: "#35664d",
        background: "#fffefa",
        font: "geist",
        radius: "small",
        confirmed: false,
      },
    ],
    knowledgeSources: [],
    knowledgeChunks: [],
    signalDefinitions: [],
    accounts: [],
    contacts: [],
    productWorkspaces: [],
    identities: [],
    productEvents: [],
    memories: [],
    connections: [
      {
        provider: "events",
        name: "Product events",
        description: "Direct API and PostHog webhooks",
        capabilities: ["Receive product signals", "Resolve identities"],
      },
      {
        provider: "agentmail",
        name: "AgentMail",
        description: "A shared inbox for timely conversations",
        capabilities: ["Send approved emails", "Receive replies"],
      },
      {
        provider: "hubspot",
        name: "HubSpot",
        description: "Customer-owned CRM, connected through Composio",
        capabilities: [
          "Find companies and contacts",
          "Update lifecycle",
          "Record activity",
        ],
      },
      {
        provider: "context",
        name: "Context.dev",
        description: "Company context, with the sources attached",
        capabilities: ["Research websites", "Enrich accounts"],
      },
      {
        provider: "retell",
        name: "Retell",
        description: "A calling path for opted-in contacts",
        capabilities: ["Start approved calls", "Receive call outcomes"],
      },
      {
        provider: "model",
        name: "AI Gateway",
        description:
          "Structured generation using your deployment’s model account",
        capabilities: ["Generate business briefs", "Draft personalized pages"],
      },
    ].map((c) => ({
      ...c,
      ...base,
      id: `connection-${c.provider}`,
      provider: c.provider as Dataset["connections"][number]["provider"],
      status: "disconnected",
      owner: user.name,
      scope: ["model", "context"].includes(c.provider)
        ? "deployment"
        : "workspace",
    })),
    policies: [
      {
        ...base,
        id: "policy-1",
        version: 1,
        mode: "copilot",
        overrides: {},
        pausedChannels: [],
        minEmployees: 25,
        requireIntent: false,
        quietStart: 20,
        quietEnd: 8,
        maxContactPerDay: 1,
        maxAccountPerDay: 2,
        approvalTtlHours: 168,
        createdAt: now,
        actor: user.id,
      },
    ],
    agentRuns: [],
    actions: [],
    approvals: [],
    artifacts: [],
    pageSpecs: [],
    conversations: [],
    auditEntries: [],
    outcomes: [],
    policyProposals: [],
    crmChanges: [],
  };
}
